name: Deploy SNAPSHOT

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Set up ossrh
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache m2 package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn test

  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Set up ossrh
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache m2 package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: python script
        run: |
          import xml.etree.ElementTree as ET
          xml_file = 'pom.xml'
          tree = ET.parse(xml_file)
          version = tree.find("{http://maven.apache.org/POM/4.0.0}version")
          print(version.text + "-SNAPSHOT")
          tree.find("{http://maven.apache.org/POM/4.0.0}version").text = 'Good'
          ET.register_namespace("", "http://maven.apache.org/POM/4.0.0")
          tree.write(xml_file, "utf-8", True)
        shell: python
      - run: cat pom.xml
